### ISSUE TITLE
Error: Invalid template interpolation value

### ISSUE THREAD

**Issue by sharathunni** [xFreed0m/Disruption#1]
I'm not a terraform expert, but seems like there are some errors in the template. Can you take a look?

Error: Invalid template interpolation value

  on 10-machines_config.tf line 14, in locals:
  14:   win7_set_dns         = "netsh interface ip set dns 'Local Area Connection' static ${var.int_dns_address}"
    |----------------
    | var.int_dns_address is tuple with 1 element

Cannot include the given value in a string template: string required.

Error: Invalid template interpolation value

  on 10-machines_config.tf line 28, in locals:
  28:   set_dns                 = "Set-DnsClientServerAddress -InterfaceAlias 'Ethernet' -ServerAddresses ('${var.int_dns_address}', '1.1.1.1')"
    |----------------
    | var.int_dns_address is tuple with 1 element

Cannot include the given value in a string template: string required.

Error: failed to execute "./whatismyip.sh":   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    36  100    36    0     0    202      0 --:--:-- --:--:-- --:--:--   203
./whatismyip.sh: line 4: jq: command not found

  on 3-secgroup_storage.tf line 2, in data "external" "whatismyip":
   2: data "external" "whatismyip" {

**Comment by dmoore44** [comment]
I had to do a little bit of troubleshooting to get this to work...

1. @xFreed0m's original syntax appears to be an older variety, so if you recently downloaded the terraform binary, you'll want to run "terraform 0.12upgrade -force" - that should fix many of the syntactical errors.
2. In variables.tf, the default value for "int_dns_address" is declared as a list ["192.168.x.x"], and terraform bitches about it. Remove the brackets, and you should be good to go.
3. If you're running terraform on a Mac, you're not going to have the jq binary installed, which will foul up the "whatismyip" script - just do a brew install jq to resolve that dependency.

**Comment by xFreed0m** [comment]
thanks @dmoore44 !

@sharathunni , i've pushed an updated version with the new syntax.
